/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjetoFinal_1000;

import javax.swing.JOptionPane;

/**
 *
 * @author DHEIVERODRIGUESFUCK
 */
public class TelaBatalhaBruxa extends javax.swing.JFrame {

    private Personagem personagem;
    private Inimigo inimigo = new Inimigo("Bruxa", 8, 8, 8, 1);
    int etapa = 0;
    int numeroDado;

    public TelaBatalhaBruxa() {
        initComponents();
    }

    public TelaBatalhaBruxa(Personagem personagem) {
        initComponents();
        this.personagem = personagem;
        buttonAvanca.setVisible(false);
        setLocationRelativeTo(null);
        progreesLife();
        progressBars();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressInimigo = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        progressMagia = new javax.swing.JProgressBar();
        labelVida2 = new javax.swing.JLabel();
        labelMana2 = new javax.swing.JLabel();
        progressVigor = new javax.swing.JProgressBar();
        buttonFugir2 = new javax.swing.JButton();
        buttonDice = new javax.swing.JButton();
        buttonAtacar3 = new javax.swing.JButton();
        buttonAvanca = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        progressInimigo.setBackground(new java.awt.Color(255, 0, 0));
        progressInimigo.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A Bruxa");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de tela 2025-11-19 194630.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        progressMagia.setBackground(new java.awt.Color(0, 102, 255));
        progressMagia.setForeground(new java.awt.Color(0, 102, 255));

        labelVida2.setBackground(new java.awt.Color(255, 255, 255));
        labelVida2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVida2.setForeground(new java.awt.Color(255, 255, 255));
        labelVida2.setText("Vida:");

        labelMana2.setBackground(new java.awt.Color(255, 255, 255));
        labelMana2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelMana2.setForeground(new java.awt.Color(255, 255, 255));
        labelMana2.setText("Mana:");

        progressVigor.setBackground(new java.awt.Color(51, 255, 0));
        progressVigor.setForeground(new java.awt.Color(153, 255, 0));

        buttonFugir2.setBackground(new java.awt.Color(0, 0, 0));
        buttonFugir2.setForeground(new java.awt.Color(255, 255, 255));
        buttonFugir2.setText("Fugir");
        buttonFugir2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonFugir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFugir2ActionPerformed(evt);
            }
        });

        buttonDice.setBackground(new java.awt.Color(0, 0, 0));
        buttonDice.setForeground(new java.awt.Color(255, 255, 255));
        buttonDice.setText("Dados");
        buttonDice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiceActionPerformed(evt);
            }
        });

        buttonAtacar3.setBackground(new java.awt.Color(0, 0, 0));
        buttonAtacar3.setForeground(new java.awt.Color(255, 255, 255));
        buttonAtacar3.setText("Atacar");
        buttonAtacar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonAtacar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtacar3ActionPerformed(evt);
            }
        });

        buttonAvanca.setBackground(new java.awt.Color(0, 0, 0));
        buttonAvanca.setForeground(new java.awt.Color(255, 255, 255));
        buttonAvanca.setText("Avança");
        buttonAvanca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonAvanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvancaActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de tela 2025-11-19 213645.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(labelMana2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(progressVigor, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(progressMagia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(buttonDice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonAtacar3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonFugir2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                .addComponent(buttonAvanca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressVigor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVida2))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressMagia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMana2))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(buttonAvanca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(buttonDice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAtacar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFugir2)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel2)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(progressInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(529, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(progressInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFugir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFugir2ActionPerformed
        if (!Jogo.escape(personagem, inimigo)) {
            if (inimigo.attack(personagem, inimigo)) {
                JOptionPane.showMessageDialog(this, "Voce foi lento demais \n nao conseguiu escapar \n Dano recebido: " + inimigo.getStrength());
            } else {
                JOptionPane.showMessageDialog(this, "O inimigo e incompetente \n Inimigo errou o ataque");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Voce conseguiu escapar!!!");
            new TelaTerceira(personagem).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_buttonFugir2ActionPerformed

    private void buttonDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiceActionPerformed
        if (etapa > 0) {
            JOptionPane.showMessageDialog(this, "ta tentando ne filho nois ta pesseia");
        }
        numeroDado = Dados.useDice();
        JOptionPane.showMessageDialog(this, "Voce girou o dado! \n Resultado: " + numeroDado);
        etapa = 1;
    }//GEN-LAST:event_buttonDiceActionPerformed

    private void buttonAtacar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtacar3ActionPerformed
        if (etapa > 0) {
            attack();
            if (personagem.estaMorto()) {
                viewButton1();
            }
            if (inimigo.estaMorto()) {
                JOptionPane.showMessageDialog(this, "Voce derrotou " + inimigo.getName());
                viewButton2();
            }
        } else {
            JOptionPane.showMessageDialog(this, "voce tem que girar o dado primeiro!");
        }
        etapa = 0;
    }//GEN-LAST:event_buttonAtacar3ActionPerformed

    private void buttonAvancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvancaActionPerformed
        new TelaTerceira(personagem).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonAvancaActionPerformed

    public void progressBars() {
        // vida
        progressVigor.setValue(personagem.getLife());
        progressVigor.setStringPainted(true);
        progressVigor.setString(personagem.getLife() + "/" + progressVigor.getMaximum());
        // mana
        progressMagia.setValue(personagem.getMana());
        progressMagia.setStringPainted(true);
        progressMagia.setString(personagem.getMana() + "/" + progressMagia.getMaximum());
        //inimigo
        progressInimigo.setValue(inimigo.getLife());
        progressInimigo.setStringPainted(true);
        progressInimigo.setString(inimigo.getLife() + "/" + progressInimigo.getMaximum());
    }

    public void attack() {
        //aumentando forca do personagem baseado no numero do dado
        int forca1 = personagem.getStrength();
        System.out.println(forca1);
        personagem.setStrength(forca1 + numeroDado);
        System.out.println(personagem.getStrength());
        //combate
        inimigo.attack(personagem, inimigo);
        if (personagem.attack(personagem, inimigo)) {
            JOptionPane.showMessageDialog(this, "voce acertou e causo" + personagem.getStrength());
        } else {
            JOptionPane.showMessageDialog(this, "Errou!!!!");
        }

        //forca volta ao normal
        personagem.setStrength(forca1);
        System.out.println(personagem.getStrength());
        //mostar barra de vida atualizado apos attack do personagem
        progressVigor.setValue(personagem.getLife());
        progressVigor.setString(personagem.getLife() + "/" + progressVigor.getMaximum());
        //mostar barra de vida atualizado apos attack do inimigo
        progressInimigo.setValue(inimigo.getLife());
        progressInimigo.setString(inimigo.getLife() + "/" + progressInimigo.getMaximum());
    }

    //mostra os botao se o personagem morrer
    public void viewButton1() {
        //nao visivel
        buttonAtacar3.setVisible(false);
        buttonFugir2.setVisible(false);
        buttonDice.setVisible(false);
    }

    public void viewButton2() {
        //nao visivel
        buttonAtacar3.setVisible(false);
        buttonDice.setVisible(false);
        buttonFugir2.setVisible(false);
        //visivel
        buttonAvanca.setVisible(true);
    }

    public void progreesLife() {
        progressVigor.setMaximum(personagem.getLife());
        progressMagia.setMaximum(personagem.getMana());
        progressInimigo.setMaximum(inimigo.getLife());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalhaBruxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalhaBruxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalhaBruxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalhaBruxa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalhaBruxa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    // Variables declaration - do not modify

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAtacar3;
    private javax.swing.JButton buttonAvanca;
    private javax.swing.JButton buttonDice;
    private javax.swing.JButton buttonFugir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelMana2;
    private javax.swing.JLabel labelVida2;
    private javax.swing.JProgressBar progressInimigo;
    private javax.swing.JProgressBar progressMagia;
    private javax.swing.JProgressBar progressVigor;
    // End of variables declaration//GEN-END:variables
}
